follower:
  left_arm:
    server_port: 11333
  right_arm:
    server_port: 11334
  joint_labels:
    left:
      joint_1: Joint 1
      joint_2: Joint 2
      joint_3: Joint 3
      joint_4: Joint 4
      joint_5: Joint 5
      joint_6: Joint 6
      gripper: Gripper
    right:
      joint_1: Joint 1
      joint_2: Joint 2
      joint_3: Joint 3
      joint_4: Joint 4
      joint_5: Joint 5
      joint_6: Joint 6
      gripper: Gripper

leader:
  left_arm:
    port: /dev/ttyACM0
  right_arm:
    port: /dev/ttyACM1
  joint_labels:
    left:
      joint_1: Joint 1
      joint_2: Joint 2
      joint_3: Joint 3
      joint_4: Joint 4
      joint_5: Joint 5
      joint_6: Joint 6
      gripper: Gripper
    right:
      joint_1: Joint 1
      joint_2: Joint 2
      joint_3: Joint 3
      joint_4: Joint 4
      joint_5: Joint 5
      joint_6: Joint 6
      gripper: Gripper

cameras:
  labels:
    left_wrist: Left Wrist
    right_wrist: Right Wrist
    topdown: Topdown
  devices:
    left_wrist:
      path: /dev/video2
      width: 640
      height: 480
      fps: 30
    right_wrist:
      path: /dev/video0
      width: 640
      height: 480
      fps: 30
    topdown:
      path: /dev/video4
      width: 3200
      height: 1200
      fps: 15
      fourcc: MJPG
