collision:
  ground_z: -0.07
  end_effector_length: 0.15
  max_joint_step: [0.5, 0.35, 0.3, 0.3, 0.7, 0.7]  # radians per action, per joint

follower:
  left_arm:
    can_port: can0
    server_port: 11333
    motors:
      joint_1:
        label: Joint 1
      joint_2:
        label: Joint 2
      joint_3:
        label: Joint 3
      joint_4:
        label: Joint 4
      joint_5:
        label: Joint 5
      joint_6:
        label: Joint 6
      gripper:
        label: Gripper
  right_arm:
    can_port: can1
    server_port: 11334
    motors:
      joint_1:
        label: Joint 1
      joint_2:
        label: Joint 2
      joint_3:
        label: Joint 3
      joint_4:
        label: Joint 4
      joint_5:
        label: Joint 5
      joint_6:
        label: Joint 6
      gripper:
        label: Gripper

leader:
  left_arm:
    port: /dev/leader-left
    motors:
      joint_1:
        id: 1
        model: xm430-w350
        norm_mode: DEGREES
        calibration_scale: 1.0
        label: Joint 1
      joint_2:
        id: 2
        model: xm430-w350
        norm_mode: DEGREES
        calibration_scale: 1.0
        label: Joint 2
      joint_3:
        id: 3
        model: xm430-w350
        norm_mode: DEGREES
        calibration_scale: -1.0
        label: Joint 3
      joint_4:
        id: 4
        model: xl330-m077
        norm_mode: DEGREES
        calibration_scale: 1.0
        label: Joint 4
      joint_5:
        id: 5
        model: xl330-m077
        norm_mode: DEGREES
        calibration_scale: 1.0
        label: Joint 5
      joint_6:
        id: 6
        model: xl330-m077
        norm_mode: DEGREES
        calibration_scale: 1.0
        label: Joint 6
      gripper:
        id: 7
        model: xl330-m077
        norm_mode: DEGREES
        label: Gripper
  right_arm:
    port: /dev/leader-right
    motors:
      joint_1:
        id: 8
        model: xm430-w350
        norm_mode: DEGREES
        calibration_scale: 1.0
        label: Joint 1
      joint_2:
        id: 9
        model: xm430-w350
        norm_mode: DEGREES
        calibration_scale: 1.0
        label: Joint 2
      joint_3:
        id: 10
        model: xm430-w210
        norm_mode: DEGREES
        calibration_scale: 1.0
        label: Joint 3
      joint_4:
        id: 11
        model: xl330-m077
        norm_mode: DEGREES
        calibration_scale: -1.0
        label: Joint 4
      joint_5:
        id: 12
        model: xl330-m077
        norm_mode: DEGREES
        calibration_scale: 1.0
        label: Joint 5
      joint_6:
        id: 13
        model: xl330-m077
        norm_mode: DEGREES
        calibration_scale: 1.0
        label: Joint 6
      gripper:
        id: 14
        model: xl330-m077
        norm_mode: DEGREES
        label: Gripper

cameras:
  labels:
    left_wrist: Left Wrist
    right_wrist: Right Wrist
    topdown: Topdown
  configs:
    right_wrist:
      type: opencv-cached
      index_or_path: /dev/video0
      fps: 30
      width: 640
      height: 480
      fourcc: MJPG
      auto_exposure_enabled: true
      auto_exposure_target: 120
      auto_exposure_min: 20
      auto_exposure_max: 130
      shm_key: cam_right_wrist
    left_wrist:
      type: opencv-cached
      index_or_path: /dev/video2
      fps: 30
      width: 640
      height: 480
      fourcc: MJPG
      auto_exposure_enabled: true
      auto_exposure_target: 120
      auto_exposure_min: 20
      auto_exposure_max: 130
      shm_key: cam_left_wrist
    topdown:
      type: intelrealsense-cached
      serial_number_or_name: "203522250539"
      warmup_s: 3
      fps: 30
      width: 640
      height: 480
